apt remove webapp-manager -y
apt remove thingy -y
apt remove hexchat -y
apt remove drawing -y
apt remove pix -y
apt remove pix-dbg -y
apt remove celluloid -y
apt remove warpinator -y
apt remove transmission-gtk -y
apt remove timeshift -y
apt remove rhythmbox -y
apt remove rhythmbox-plugins -y
apt remove rhythmbox-plugin-tray-icon -y
apt remove hypnotix -y
apt remove libreoffice-writer -y
apt remove libreoffice-math -y
apt remove libreoffice-writer -y
apt remove libreoffice-draw -y
apt remove libreoffice-* -y
apt remove thunderbird -y
apt remove thunderbird-* -y
